# Docker compose file for an example redis stack server
services:
    redis-stack:
        container_name: redis-stack
        volumes:
          - /tmp/docker/redis-stack/data:/data
        ports:
            - "6379:6379"
            - "8001:8001"
        restart: always
        image: redis/redis-stack:latest
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            timeout: 30s
            retries: 5
            start_period: 10s