---
- name: "Pi Hole"
  hosts: pi-hole
  gather_facts: false
  become: true
  tasks:
    - name: Update & upgrade package manager
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
    - name: Update Pi Hole
      ansible.builtin.command: "pihole -up"
      register: pihole_update
      changed_when: pihole_update.stdout.find('Everything is up to date') == -1